### ISSUE TITLE
static + non static

### ISSUE THREAD

**Issue by roymilder** [kabamgamer/autoTest#1]
Hey @kabamgamer 

Graag de code zo aanpassen:

Stap 1 maak via een static function een nieuwe auto waarbij je kan kiezen uit: "Merk" & "Kleur".
Sla die settings op in een cookie
Stap 2, nadat de auto gemaakt is wil ik exact dezelfde auto kunnen starten. Dus zelfde merk, zelfde kleur. Nadat deze gestart is wil ik dat het scherm toont wat het merk en de kleur is van de auto die je zojuist gestart hebt.

**Comment by kabamgamer** [comment]
Ha @roymilder 

De code is aangepast!

Je kan een auto samenstellen, je kan hem starten en zien welke is gestart en je kan heel de pagina opnieuw laden en dan nog zien welke auto je de vorige keer had gestart. (Cookie blijft 24 uur bestaan)
