### ISSUE TITLE
N auto's kunnen starten

### ISSUE THREAD

**Issue by roymilder** [kabamgamer/autoTest#2]
Ajb code zo aanpassen dat ik verschillende auto's kan starten, en daar ook tussen kan wisselen.
Ook wil ik alles kunnen resetten.

Dit graag maken op basis van een Github project: 
![image](https://user-images.githubusercontent.com/2341834/36086509-2d4b8f40-0fcd-11e8-888b-2fdc189399d6.png)

En aan ieder los issue je code koppelen!

**Comment by kabamgamer** [comment]
Ha @roymilder 

Ook deze opdracht is afgerond. Code is geüpload!
